Set baseUrl in tsconfig.json to allow imports relative to root
For some reason, the import paths can't be changed in the gallery, it
results in errors like these:

    Error: Can't walk dependency graph: Cannot find module 'app/js/utils/logos'

The TS compiler does find the files, I see different errors if I change
baseUrl to something invalid, so these errors seem Browserify related.